"""Initial SQLite migration

Revision ID: 6f250a8e0fa5
Revises: 
Create Date: 2026-04-03 12:33:52.509431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f250a8e0fa5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('unique_code', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organization_unique_code'), ['unique_code'], unique=True)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('role', sa.Enum('admin', 'manager', 'employee', name='userrole'), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('employee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('position', sa.String(length=50), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('profile_pic', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employee_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_employee_user_id'), ['user_id'], unique=True)

    op.create_table('activity_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=30), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('entity_name', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_log_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_log_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_log_organization_id'), ['organization_id'], unique=False)

    op.create_table('lead',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('company', sa.String(length=100), nullable=True),
    sa.Column('source', sa.Enum('Website', 'Google', 'Social Media', 'Referral', 'Walk-in', 'Other', name='leadsource'), nullable=True),
    sa.Column('status', sa.Enum('New', 'Active', 'Inactive', 'Prospect', name='leadstatus'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('gst_number', sa.String(length=15), nullable=True),
    sa.Column('trade_name', sa.String(length=200), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('pincode', sa.String(length=10), nullable=True),
    sa.Column('business_type', sa.String(length=100), nullable=True),
    sa.Column('gst_status', sa.String(length=50), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number')
    )
    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lead_assigned_to'), ['assigned_to'], unique=False)
        batch_op.create_index(batch_op.f('ix_lead_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_lead_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_lead_gst_number'), ['gst_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_lead_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lead_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_lead_updated_by'), ['updated_by'], unique=False)

    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('company', sa.String(length=100), nullable=True),
    sa.Column('source', sa.Enum('Website', 'Google', 'Social Media', 'Referral', 'Walk-in', 'Other', name='leadsource'), nullable=True),
    sa.Column('status', sa.Enum('New', 'Requirement Understood', 'Measurement Scheduled', 'Quotation Sent', 'Follow Up', 'Order Confirmed', 'In Production', 'Ready for Dispatch', 'Installation Scheduled', 'Installation Done', 'Completed', 'Cancelled', name='customerstatus'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('gst_number', sa.String(length=15), nullable=True),
    sa.Column('trade_name', sa.String(length=200), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('pincode', sa.String(length=10), nullable=True),
    sa.Column('business_type', sa.String(length=100), nullable=True),
    sa.Column('gst_status', sa.String(length=50), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['lead.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number')
    )
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_assigned_to'), ['assigned_to'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_customer_gst_number'), ['gst_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_lead_id'), ['lead_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_customer_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_updated_by'), ['updated_by'], unique=False)

    op.create_table('lead_activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('activity_type', sa.Enum('Call', 'Meeting', 'Email', 'Note', 'Task', name='activitytype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['lead.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lead_activity', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lead_activity_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_lead_activity_lead_id'), ['lead_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lead_activity_organization_id'), ['organization_id'], unique=False)

    op.create_table('customer_document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customer_document', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_document_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_document_organization_id'), ['organization_id'], unique=False)

    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('Planning', 'In Progress', 'On Hold', 'Completed', 'Cancelled', name='projectstatus'), nullable=True),
    sa.Column('work_type', sa.Enum('Glass', 'Hardware', 'Mirror', name='projectworktype'), nullable=True),
    sa.Column('category', sa.Enum('Commercial', 'Residential', name='projectcategory'), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_assigned_to'), ['assigned_to'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_updated_by'), ['updated_by'], unique=False)

    op.create_table('invoice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sa.String(length=20), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('gst_amount', sa.Float(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('Unpaid', 'Paid', 'Partially Paid', 'Cancelled', 'Overdue', name='invoicestatus'), nullable=True),
    sa.Column('issue_date', sa.DateTime(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoice_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoice_invoice_number'), ['invoice_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_invoice_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoice_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoice_status'), ['status'], unique=False)

    op.create_table('quotation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quotation_number', sa.String(length=50), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('amendment_no', sa.String(length=50), nullable=True),
    sa.Column('measurements', sa.String(length=255), nullable=True),
    sa.Column('quote_level', sa.String(length=255), nullable=True),
    sa.Column('subtotal', sa.Float(), nullable=True),
    sa.Column('gst_amount', sa.Float(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('Draft', 'Sent', 'Accepted', 'Rejected', name='quotationstatus'), nullable=True),
    sa.Column('issue_date', sa.DateTime(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('terms_conditions', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['lead.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quotation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quotation_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quotation_lead_id'), ['lead_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quotation_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quotation_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quotation_quotation_number'), ['quotation_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_quotation_status'), ['status'], unique=False)

    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('Pending', 'In Progress', 'Completed', 'Cancelled', name='taskstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['lead.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_assigned_to'), ['assigned_to'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_lead_id'), ['lead_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_status'), ['status'], unique=False)

    op.create_table('invoice_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('rate', sa.Float(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invoice_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoice_item_invoice_id'), ['invoice_id'], unique=False)

    op.create_table('quotation_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quotation_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('width', sa.Float(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('gst_percentage', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('rate', sa.Float(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quotation_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quotation_item_quotation_id'), ['quotation_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quotation_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quotation_item_quotation_id'))

    op.drop_table('quotation_item')
    with op.batch_alter_table('invoice_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoice_item_invoice_id'))

    op.drop_table('invoice_item')
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_status'))
        batch_op.drop_index(batch_op.f('ix_task_project_id'))
        batch_op.drop_index(batch_op.f('ix_task_organization_id'))
        batch_op.drop_index(batch_op.f('ix_task_lead_id'))
        batch_op.drop_index(batch_op.f('ix_task_created_by'))
        batch_op.drop_index(batch_op.f('ix_task_assigned_to'))

    op.drop_table('task')
    with op.batch_alter_table('quotation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quotation_status'))
        batch_op.drop_index(batch_op.f('ix_quotation_quotation_number'))
        batch_op.drop_index(batch_op.f('ix_quotation_project_id'))
        batch_op.drop_index(batch_op.f('ix_quotation_organization_id'))
        batch_op.drop_index(batch_op.f('ix_quotation_lead_id'))
        batch_op.drop_index(batch_op.f('ix_quotation_customer_id'))

    op.drop_table('quotation')
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoice_status'))
        batch_op.drop_index(batch_op.f('ix_invoice_project_id'))
        batch_op.drop_index(batch_op.f('ix_invoice_organization_id'))
        batch_op.drop_index(batch_op.f('ix_invoice_invoice_number'))
        batch_op.drop_index(batch_op.f('ix_invoice_customer_id'))

    op.drop_table('invoice')
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_updated_by'))
        batch_op.drop_index(batch_op.f('ix_project_status'))
        batch_op.drop_index(batch_op.f('ix_project_organization_id'))
        batch_op.drop_index(batch_op.f('ix_project_customer_id'))
        batch_op.drop_index(batch_op.f('ix_project_created_by'))
        batch_op.drop_index(batch_op.f('ix_project_assigned_to'))

    op.drop_table('project')
    with op.batch_alter_table('customer_document', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_document_organization_id'))
        batch_op.drop_index(batch_op.f('ix_customer_document_customer_id'))

    op.drop_table('customer_document')
    with op.batch_alter_table('lead_activity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lead_activity_organization_id'))
        batch_op.drop_index(batch_op.f('ix_lead_activity_lead_id'))
        batch_op.drop_index(batch_op.f('ix_lead_activity_created_by'))

    op.drop_table('lead_activity')
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_updated_by'))
        batch_op.drop_index(batch_op.f('ix_customer_status'))
        batch_op.drop_index(batch_op.f('ix_customer_organization_id'))
        batch_op.drop_index(batch_op.f('ix_customer_lead_id'))
        batch_op.drop_index(batch_op.f('ix_customer_gst_number'))
        batch_op.drop_index(batch_op.f('ix_customer_email'))
        batch_op.drop_index(batch_op.f('ix_customer_created_by'))
        batch_op.drop_index(batch_op.f('ix_customer_assigned_to'))

    op.drop_table('customer')
    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lead_updated_by'))
        batch_op.drop_index(batch_op.f('ix_lead_status'))
        batch_op.drop_index(batch_op.f('ix_lead_organization_id'))
        batch_op.drop_index(batch_op.f('ix_lead_gst_number'))
        batch_op.drop_index(batch_op.f('ix_lead_email'))
        batch_op.drop_index(batch_op.f('ix_lead_created_by'))
        batch_op.drop_index(batch_op.f('ix_lead_assigned_to'))

    op.drop_table('lead')
    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_log_organization_id'))
        batch_op.drop_index(batch_op.f('ix_activity_log_created_at'))
        batch_op.drop_index(batch_op.f('ix_activity_log_actor_id'))

    op.drop_table('activity_log')
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employee_user_id'))
        batch_op.drop_index(batch_op.f('ix_employee_organization_id'))

    op.drop_table('employee')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_organization_id'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organization_unique_code'))

    op.drop_table('organization')
    # ### end Alembic commands ###
